AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - vendor/**/*

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

RSpec/SpecFilePathFormat:
  Enabled: false

Style/LineLength:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Naming/FileName:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rake
  - rubocop-rspec
