language: ruby
arch:
  - amd64
  - ppc64le
  
cache: bundler

before_install:
  - gem update --system

rvm:
  - 2.7.2
  - 2.6.5
  - 2.4.0
  - 2.3.1
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: ruby-head
      arch: ppc64le
    - rvm: jruby-head
      arch: ppc64le
